# Generated by Django 2.0.6 on 2018-09-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='product_caption',
            field=models.TextField(default='Amazing Product... 5/7 would buy again.', max_length=128),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product_review',
            field=models.TextField(default='12 words cant do justice to this product, wait for full review.', max_length=100000),
        ),
    ]
