# Generated by Django 2.0.6 on 2018-09-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180929_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_of_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
