# Generated by Django 2.0.6 on 2018-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_products_number_of_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(default='http://placehold.it/230x260', max_length=10000),
        ),
        migrations.AlterField(
            model_name='products',
            name='affiliate_url',
            field=models.URLField(help_text='Product Affiliate link.', max_length=10000),
        ),
    ]
