# Generated by Django 2.0.6 on 2018-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180929_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_display',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
