# Generated by Django 2.0.6 on 2018-09-29 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_products_image_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='using_since',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
