# Generated by Django 2.0.6 on 2018-09-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180929_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
